package squixdev.achievementsplus.common;


import java.util.Hashtable;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

//Nouvelle version : changer le ModID, la variable VERSION

@Mod(modid = "achievementsplus", name = "Achievements +", version = "1.0.0")

public class AchievementsPlus {

	
  public static final String MODID = "achievementsplus";
  public static final String VERSION = "1.0.0";
  public static final String MODNAME = "Achievements +";
  public static final String MODAUTHOR = "SquixDev, Squix";
  public static final String MODDESCRIPTION = "This mod brings to Minecraft's achievements a new dimension.";
  public static final String MODURL = "http://squixdev.appspot.com";
  public static final String MODLOGO = "achievementsplus_logo.png";
  
  static Hashtable<String, String> AchievementsTriggered = new Hashtable<String, String>();
  
  @SidedProxy(clientSide = "squixdev.achievementsplus.client.ProxyClient", serverSide = "squixdev.achievementsplus.common.ProxyCommon")
	public static ProxyCommon proxy;
  
  @EventHandler
  public void preInit(FMLPreInitializationEvent event) {
  	
  	// hard-code mod information so don't need mcmod.info file
      event.getModMetadata().autogenerated = false ; // stops it from complaining about missing mcmod.info
      event.getModMetadata().authorList.add(EnumChatFormatting.RED+MODAUTHOR);
      event.getModMetadata().description = EnumChatFormatting.YELLOW+MODDESCRIPTION;
      event.getModMetadata().url = MODURL;
      event.getModMetadata().logoFile = MODLOGO;
  }
  
  @EventHandler
  public void init(FMLInitializationEvent event)
  
  {
  	proxy.initAchievements();
  	FMLCommonHandler.instance().bus().register(proxy);
  	MinecraftForge.EVENT_BUS.register(new AchievementsHandler());
  }

  
}