package squixdev.removehudbutnothand.common;

import java.io.File;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import squixdev.removehudbutnothand.client.ProxyClient;
import squixdev.removehudbutnothand.client.VersionChecker;



//Nouvelle version : changer le ModID, la variable VERSION

@Mod(modid = "removehudbutnothand", name = "Remove HUD but Not Hand", version = "1.0.3",
guiFactory = "squixdev.removehudbutnothand.common.GuiFactoryRHBNH")

public class RemoveHUDbutNotHand {

	// Version checking instance
	public static VersionChecker versionChecker;
	public static boolean haveWarnedVersionOutOfDate = false;
	
	public static final String MODID = "removehudbutnothand";
    public static final String VERSION = "1.0.3";
    public static final String MODNAME = "Remove HUD but Not Hand";
    public static final String MODAUTHOR = "SquixDev, Squix";
    public static final String MODDESCRIPTION = "This mod allow you to toggle minecraft HUD (like pressing F1) but with keeping of the player hand. Helpful for realistic first-Person Cinematics !!";
    public static final String MODURL = "http://squixdev.appspot.com";
    public static final String MODLOGO = "removehudbutnothand_logo.png";
    
    public static Boolean hideHud = false;
    
    public static Configuration config;
	public static File configFile;
    
    //Config variables
    
    public static Boolean hideHealth;
    public static Boolean hideAir;
    public static Boolean hideHealthMount;
    public static Boolean hideFood;
    public static Boolean hideArmor;
    public static Boolean hideHelmet;
    public static Boolean hideJumpBar;
    public static Boolean hideCrosshairs;
    public static Boolean hideExp;
    public static Boolean hideHotbar;
    public static Boolean hideBossHealth;
    public static Boolean hideChat;
    
    public static Boolean hideItemHeldTooltip;
    public static Boolean showWelcomeMessage;
    public static Boolean checkVersion;
 
    @SidedProxy(clientSide = "squixdev.removehudbutnothand.client.ProxyClient", serverSide = "squixdev.removehudbutnothand.client.ProxyCommon")
	public static ProxyCommon proxy;
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
    	proxy.initConfig(event);
    	// hard-code mod information so don't need mcmod.info file
        event.getModMetadata().autogenerated = false ; // stops it from complaining about missing mcmod.info
        event.getModMetadata().authorList.add(EnumChatFormatting.RED+MODAUTHOR);
        event.getModMetadata().description = EnumChatFormatting.YELLOW+MODDESCRIPTION;
        event.getModMetadata().url = MODURL;
        event.getModMetadata().logoFile = MODLOGO;
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    
    {
    	
    	FMLCommonHandler.instance().bus().register(proxy);
    	MinecraftForge.EVENT_BUS.register(new HudRenderHandler());
    }
    
    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    
    {
    	
    	if(checkVersion) {
    	 ProxyClient.versionCheck();
    	}
    	
    }


}
